/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "brand-deep": "#A61C2E",
        "brand-vivid": "#E63946",
        "brand-caution-bg": "#F8D7DC",
        "brand-black": "#1A1A1A",
        "brand-white": "#FFFFFF",
        "brand-offwhite": "#F7F5F2",
        "text-muted": "#6B6560",
        "success": "#2E9E5B",
        "secondary": "#b7102a",
        "surface-dim": "#dcd9d9",
        "text-warm-gray": "#6B6560",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#ffb3b2",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary-fixed": "#410007",
        "on-error-container": "#93000a",
        "inverse-primary": "#ffb3b2",
        "on-surface": "#1c1b1b",
        "on-primary-container": "#ffb9b8",
        "on-surface-variant": "#594140",
        "surface": "#fcf9f8",
        "on-secondary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#005229",
        "tertiary-container": "#006332",
        "background-off-white": "#F7F5F2",
        "on-primary-fixed-variant": "#910621",
        "surface-container-highest": "#e5e2e1",
        "surface-container-low": "#f6f3f2",
        "surface-bright": "#fcf9f8",
        "on-secondary-fixed-variant": "#92001c",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#313030",
        "secondary-fixed-dim": "#ffb3b1",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#75e096",
        "surface-tint": "#b32736",
        "primary": "#82001b",
        "error": "#ba1a1a",
        "secondary-container": "#db313f",
        "surface-container-high": "#eae7e7",
        "on-background": "#1c1b1b",
        "secondary-fixed": "#ffdad8",
        "outline-variant": "#e1bebd",
        "on-tertiary-fixed": "#00210d",
        "primary-fixed": "#ffdad9",
        "background": "#fcf9f8",
        "surface-variant": "#e5e2e1",
        "tertiary": "#004923",
        "outline": "#8d706f",
        "tertiary-fixed-dim": "#71dc92",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "primary-container": "#a61c2e",
        "caution-tint": "#F8D7DC",
        "tertiary-fixed": "#8df9ac",
        "on-primary-fixed": "#410009",
        "surface-container": "#f0eded",
        "vivid-red": "#E63946"
      },
      spacing: {
        "margin-page": "48px",
        "sidebar-width": "260px",
        "stack-md": "16px",
        "gutter": "24px",
        "container-max": "1200px",
        "stack-sm": "8px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "headline-sm": ["Noto Sans"],
        "body-lg": ["Noto Sans"],
        "label-sm": ["Noto Sans"],
        "body-md": ["Noto Sans"],
        "headline-md": ["Noto Sans"],
        "label-lg": ["Noto Sans"],
        "headline-lg": ["Noto Sans"],
        "display-lg": ["Noto Sans"]
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
